### ISSUE TITLE
Disable toast rendering but keep the duration with pausable prop behaviour

### ISSUE THREAD

**Issue by FluffyDiscord** [zerodevx/svelte-toast#48]
I would be great to just skip progress bar rendering with a prop, but still keep the duration + pausable behaviour.

The proposed [bandate solution](https://github.com/zerodevx/svelte-toast/pull/34) doesn't behave as described above. Duplicating the logic outside of the toast envinronment is a bit weird when it's aready built in.

**Comment by zerodevx** [comment]
You can just set the progress bar height to zero.

```html
<script>
import { toast, SvelteToast } from '@zerodevx/svelte-toast'

const options = {
  duration: 8000,
  pausable: true,
  theme: { '--toastBarHeight': 0 }
}
</script>

<button on:click={() => toast.push('Hello world')}>Emit</button>

<SvelteToast {options} />
```

**Comment by FluffyDiscord** [comment]
Yes I can (currently forcing display: none), but it's still rendering/updating unnecessary html code.

![pic](https://user-images.githubusercontent.com/10332247/182955678-315d120e-fc3e-4b14-9422-ccd4caef27f5.png)

**Comment by zerodevx** [comment]
Oh I see you meant to disable the DOM update completely. The implementation doesn't support this if you're making use of `duration`. The toast by design uses the progress bar tween to calculate/simulate duration - when progress reaches terminal position (either 0 or 1), the toast dismisses automatically. However, this update operation isn't expensive because it doesn't trigger a browser reflow.
